version: "3.8"
services:

    mongo:
        image: mongo:latest
        restart: always
        env_file:
            - mongo.env

    mongo-express:
        image: mongo-express:latest
        restart: always
        ports:
            - 8081:8081
        env_file:
            -   mongo-express.env
        depends_on:
            - mongo

    admin:
        image: tuwkan2005/admin-server:latest
        restart: always
        ports:
            - 9003:9003

    client:
        image: tuwkan2005/client-service:latest
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - admin
            - mongo
        env_file:
            - client-service.env