version: "3.8"
services:

    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin1!

    mongo-express:
        image: mongo-express:latest
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin1!
        depends_on:
            -   mongo

    admin:
        image: tuwkan2005/admin-server:latest
        restart: always
        ports:
        -   9003:9003

    client:
        image: tuwkan2005/client-service:latest
        restart: always
        ports:
        -   8080:8080
        depends_on:
            - admin
            - mongo